language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - mysql
  
script:
  - cd backend/nistagram-monolith
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
