language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - mysql

addons:
  sonarcloud:
    organization: "gojko1001"
    token:
      secure: "e6R8MG1LC469UlRV/z4uvQlFU9LnzjQlIz5Oe+uxy0jMozMkQSpm3/f1+8UirZ7G/ZuotkPjLfYWklqi6NOUVRy0qC48H7uU2S/yY3ZHEjWEtZPRhTZfyrcwAuLc6svEhLP1VPBqWpOmZ2CB9mG7GiAiuDzUFHTzl1gnTDWO+UpDr/jN30FWutmNrZuBkW4DLK5lmRVqPSy695pXrFbgHUTVYeAZ72CIhhvk7d7Mlpbszth2Z2dj1YJU9Q8js8Jrd8vEGd4+OvIz/AcQDRZ3iJyWIOjCAbKmpbTr+A9cmrTYOdxMbXvV7KYaKEQjeU1hDPldmXIb1HHPLOLZOryqt9H+/SznwJs4YnBiTVRB4KAtNvfE7LqxhhPI6Ltr7F0rSo4uxtrmp/v5z3UIXZTh6LKi/lLp4X9wXHMo/gIXp51F6hqSa9HYjcmbFF129mBs9Vcr/yjp9+wrpYjexgH1q7TUDaUBAcWq7I4puOwHkFXnB1fN1JOfV/mqo7UAXivxX2IPN22UAvYr5BAEV3FEbEv9wDr/C1YTenyvlU8YdhKokQDBSc2xKWwwYqsuN4HxZ5q7wQHlC2PFlhsN+wE3QWRrxclzbqMfXy7LcG0XXqWyUZq4FLfRYXeHZ+UsAju5QtWnVR/P488TeywbhFgcaePtecCyhT2yaBZCb29KVPw=" # encrypted value of your token

  
script:
  - cd backend/nistagram-monolith
  - chmod +x mvnw
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gojko1001_Nistagram
