language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  
services:
  - mysql

addons:
  sonarcloud:
    organization: "gojko1001"
    token:
      secure: "MlbBh2Eh1T0iU9a8hX75HECZRDxcJo8+TlVaKkQwQvKUHvq7qhP3vtGXu3lnztX1cfF/BS1KJVVoF7qV+QjB0QkeMET0WaTkIFmcXuql9XtsDTz1XVI1+5oGpnhkyOhnYcz5v/TZtxVgYiM4aO1KqpHxanbkaN4P3J5yw9ew3fgO65kHOOc2aeG2q7e/08kNYw7uC4ewm0BoK8U/77jWHYsaKUqWc26nyHjuQje2i1hamPh7X6HapPnbC25m8+MhNjCdAEvaT8zqB0/qBTkwPn8+O5c4V5i//E9TgI/U1SzigmsQzN+5o07IvChS+CBdl5xnILyQBb9arZkZcFTDO6wu4EHKHmlQ0zCgA4NgC9o2uUlWi5Myry91I9iuhbzzmtF2riK/QY11y0FVUXgeDCOU9XYjsI0NTcLf8wtEc3yYdvM+nCFX2CQAwPMQJq85LgHNYJfIfgKkWGrlRSjV0ukppO4GmdSmzEBC39FofsCTJNUtW+M543vZOtsUk3D37SdjIi44bY9L8Qx/EeifxF0/aqKniZaGYkCu7Jk6Db3JqDjeM+FJXARiJmdnE+TFKYg8NBDFpeiu7MBjs20C488WPgoAxEtapB5IWrz0yz2dvsN6kxQlzzR8pdFmL/Ej8WBNgmJVpN7PneAJ9audtm04m+13nqweaBuXAFOYQp8=" # encrypted value of your token

  
script:
  - cd backend/nistagram-monolith
  - chmod +x mvnw
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gojko1001_Nistagram
