version: "3.8"

services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build: ./backend/eureka-server
    tty: true
    networks:
      - demo
    ports:
      - "8761:8761"

  proxy-server:
    image: proxy-server
    container_name: proxy-server
    build: ./backend/proxy-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    tty: true
    networks:
      - demo
    ports:
      - "8762:8762"
    depends_on:
      - eureka-server

  frontend:
    build: ./frontend/my-app
    container_name: frontend
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - demo


  authentication-microservice:
    image: authentication-microservice
    container_name: authentication-microservice
    build:
      context: ./backend/authentication-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "3031:3031"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: authdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka-server
      - mysql

  user-microservice:
    image: user-microservice
    container_name: user-microservice
    build:
      context: ./backend/user-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "3032:3032"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: userdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka-server
      - mysql


  media-microservice:
    image: media-microservice
    container_name: media-microservice
    build:
      context: ./backend/media-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "3033:3033"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: mediadb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka-server
      - mysql


  notification-microservice:
    image: notification-microservice
    container_name: notification-microservice
    build:
      context: ./backend/notification-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "3036:3036"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: notificationdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka-server
      - mysql
      - media-microservice

  messenger-microservice:
    image: messenger-microservice
    container_name: messenger-microservice
    build:
      context: ./backend/messenger-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "3035:3035"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: chatdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka-server
      - mysql

  campaign-microservice:
    image: campaign-microservice
    container_name: campaign-microservice
    build:
      context: ./backend/campaign-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "3034:3034"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: campaigndb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka-server
      - mysql
      - media-microservice


  webshop:
    image: webshop
    container_name: webshop
    build:
      context: ./monolit-app/webshop
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "4000:4000"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: webshopdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

      
networks:
  demo:
    name: demo
    driver: bridge